[phases.setup]
nixPkgs = ["openssl"]

[phases.install]
cmds = ["npm install", "npx prisma generate"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "sh -c 'npx prisma db push --accept-data-loss && node dist/index.js'"
